# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_slug', models.SlugField()),
                ('city', models.CharField(max_length=255)),
                ('enrollment', models.IntegerField()),
                ('instate_cost', models.IntegerField()),
                ('outstate_cost', models.IntegerField()),
                ('website', models.URLField()),
                ('majors', models.URLField()),
                ('financial_aid', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SignificantMajors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='significant_majors',
            field=models.ManyToManyField(to='colleges.SignificantMajors'),
        ),
    ]
